### ISSUE TITLE
Skygfx mobile

### ISSUE THREAD

**Issue by Crdaleste** [AndroidModLoader/GTASA_SkyGfxMobile#1]
Quero alertar que essa nova versão do skygfx mobile não está mudando absolutamente nada dentro do jogo, tenho tudo certinho e mesmo assim não está mudando nada, é como se o arquivo não estivesse se quer instalado no jogo, resolvam isso por favor!

**Comment by AndroidModLoader** [comment]
English please.

**Comment by CH4CK1** [comment]
> Quero alertar que essa nova versão do skygfx mobile não está mudando absolutamente nada dentro do jogo, tenho tudo certinho e mesmo assim não está mudando nada, é como se o arquivo não estivesse se quer instalado no jogo, resolvam isso por favor!

Do not use any timecyc/colorcycle mods when you use SkyGfx. Or the settings will conflict.

Traduce este mensaje con Google.

**Comment by AndroidModLoader** [comment]
Disable colorfilter
